### ISSUE TITLE
Ajax json

### ISSUE THREAD

**Issue by gabrielhmo** [griesoft/aspnetcore-recaptcha#15]
Hi, first all, thanks for share your amazing work!

I tried your library with Ajax post and content-type: application/json, but, it seems the controller doesn't bind the "g-recaptcha-response" parameter.  I'm using [FromBody] to binding model from request parameters, and I just don't know how to catch recaptcha parameter in the decorator. Definitively, I'm doing something wrong. 

[HttpPost]
[ValidateAntiForgeryToken]
[ValidateRecaptcha(Action = "submit", ValidationFailedAction = ValidationFailedAction.ContinueRequest)]
public async Task<IActionResult> EnviarMensaje(ViewModel prospect, ValidationResponse recaptchaResponse)

I hope I've explained my self, my English is bad.

Thanks again and have a nice day!

**Comment by gabrielhmo** [comment]
> Hi, first all, thanks for share your amazing work!
> 
> I tried your library with Ajax post and content-type: application/json, but, it seems the controller doesn't bind the "g-recaptcha-response" parameter. I'm using [FromBody] to binding model from request parameters, and I just don't know how to catch recaptcha parameter in the decorator. Definitively, I'm doing something wrong.
> 
> [HttpPost] [ValidateAntiForgeryToken] [ValidateRecaptcha(Action = "submit", ValidationFailedAction = ValidationFailedAction.ContinueRequest)] public async Task EnviarMensaje(ViewModel prospect, ValidationResponse recaptchaResponse)
> 
> I hope I've explained my self, my English is bad.
> 
> Thanks again and have a nice day!

I figured out, g-recaptcha-response variable could be sending as a parameter in header request as a well. It works with Ajax post and content-type: application/json

**Comment by jooni91** [comment]
Hi, glad to hear you figured it out already.

Your solution is completely correct. Just for clarification, the validation process does try to get the token from three different places. The headers with a `G-Recaptcha-Response` key, or from the query parameters with the `g-recaptcha-response` key, or in the case of a form content type, from the form data also with the lower case `g-recaptcha-response` key.

Thanks for the kind words. You too have a nice day. 😊 

I'll close the issue as it is resolved.
