### ISSUE TITLE
Support Forward Proxy

### ISSUE THREAD

**Issue by mikocot** [griesoft/aspnetcore-recaptcha#19]
### Discussed in https://github.com/griesoft/aspnetcore-recaptcha/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **mikocot** September  8, 2022</sup>
Hi, it's not uncommon for the servers to make use of proxys to route outcoming requests, like the one needed for recaptcha. This is also the case for our company.

I can think of a workaround for now, but in the long term it would be nice to add this feature, especially, it is quite trivial. 
We'd only need to allow configuring additional values and then include them when creating an http client.
I'll submit a PR shortly.</div>

**Comment by jooni91** [comment]
Hi!

You should be able to fork this project, make changes there, and then create a PR from that.

Have a look at this:
https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by mikocot** [comment]
Yeah, I've already done it earlier, now just testing the solution. I'm familiar with the concept, don't worry.

**Comment by jooni91** [comment]
Okay, perfect. :+1:
